const categories = [
    { name: "Sadness" },
    { name: "Stress" },
    { name: "Loneliness" },
    { name: "Confused" },
    { name: "Comfort" },
    { name: "Happiness" },
    { name: "Gratitude" },
    { name: "Hope" },
    { name: "Patience" },
    { name: "Healing" },
    { name: "Guidance" },
    { name: "Strength" },
    { name: "Peace" },
    { name: "Repentance" },
    { name: "Protection" },
    { name: "Love" },
    { name: "Forgiveness" },
    { name: "Faith" },
    { name: "Mercy" },
    { name: "Charity" },
    { name: "Wisdom" },
    { name: "Contentment" },
    { name: "Trust" },
    { name: "Allah's Promise" },
    { name: "Spiritual Cleansing" },
    { name: "Justice" },
    { name: "Grief" },
    { name: "Afterlife" },
    { name: "Community" },
    { name: "Trustworthiness" },
    { name: "Fear" },
    { name: "Knowledge" },
    { name: "Success" },
    { name: "Courage" },
    { name: "Leadership" },
    { name: "Friendship" },
    { name: "Kindness" },
    { name: "Creativity" },
    { name: "Work" },
    { name: "Family" }
  ];

  export default categories;